// Generated by CoffeeScript 1.10.0
(function() {
  var Chord;

  Chord = (function() {
    var DEFAULT_OPTIONS;

    DEFAULT_OPTIONS = {
      name: "Major triad",
      formula: "135"
    };

    function Chord(options) {
      if (options == null) {
        options = DEFAULT_OPTIONS;
      }
      this.name = options.name, this.formula = options.formula;
    }

    return Chord;

  })();

  window.Chord = Chord;

}).call(this);
