// Generated by CoffeeScript 1.10.0
(function() {
  describe("echo", function() {
    beforeEach(function() {
      return spyOn(console, "log");
    });
    return it("writes a message", function() {
      echo("Hello World");
      return (expect(console.log)).toHaveBeenCalledWith("Hello World");
    });
  });

}).call(this);
