// Generated by CoffeeScript 1.10.0
(function() {
  describe("Chord", function() {
    it("has a name", function() {
      var c;
      c = new Chord;
      return (expect(c.name)).toBe("Major triad");
    });
    it("has a formula", function() {
      var c;
      c = new Chord;
      return (expect(c.formula)).toBe("135");
    });
    return it("can be constructed with a name and a formula", function() {
      var minor;
      minor = new Chord({
        name: "Minor triad",
        formula: "1b35"
      });
      (expect(minor.name)).toBe("Minor triad");
      return (expect(minor.formula)).toBe("1b35");
    });
  });

}).call(this);
